### DISCUSSION TITLE
Using product_type taxonomy in the product collection routes

### DISCUSSION THREAD

**Discussion by austriker27** [statamic-rad-pack/shopify#79] [Help] [answered]
Hello! 

I'm trying to match my current URL structure exactly for SEO purposes and having issues.

Basically for product there’s a `product_type` taxonomy I want to include the product URL

Here’s an example from a product:
```
product_type:
  - headwear
```

here’s the blueprint snippet for the product collection:
```
-
        handle: product_type
        field:
          type: terms
          taxonomies:
            - product_type
          display: 'Product Type'
          mode: select
```

Current live URL: 
`https://rainierwatch.com/shop/headwear/5-panel-logo-camper-hat/`

I'm trying to replicate with this URL:
`domain.test/shop/headwear/5-panel-logo-camper-hat`
But I get a 404 page

I tried various things like changing the product collection URL in the CP but it always gives me the 404. And I also tried mounting the collection on the shop page.
![image](https://user-images.githubusercontent.com/14855925/129430415-37c2b175-e102-41a2-89b0-a64e651f9aad.png)
 

I checked out the [docs page](https://statamic-shopify.jackwhiting.co.uk/CMS/taxonomies) and it mentioned it might not work to use shopify taxonomies on the frontend but it didnt go into specifics.  

Is this possible?
